# Generated by Django 4.1.3 on 2023-07-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_shippingaddress_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='order_item',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='order_item',
            field=models.ManyToManyField(null=True, to='store.orderitem'),
        ),
    ]
