# Generated by Django 4.1.3 on 2023-07-31 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_orderdetails_total_price_orderdetails_total_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='total_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
