# Generated by Django 4.1.3 on 2023-07-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_orderdetails_total_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='order_item',
            field=models.ManyToManyField(blank=True, to='store.orderitem'),
        ),
    ]
