# Generated by Django 4.1.3 on 2023-08-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_orderdetails_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='total_items',
            field=models.IntegerField(default=0),
        ),
    ]
