# Generated by Django 4.1.3 on 2023-08-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_orderdetails_total_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='email',
            field=models.EmailField(default='user@gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='name',
            field=models.CharField(default='user', max_length=200),
        ),
    ]
